[build.environment]
  NODE_VERSION='9.4.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER='http://localhost:8545'
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS='0x71040404f6ed612e3b1bc115ac6f1df7b3230a6f'
  REACT_APP_PROD_IMAGES_BASE_URL='https://staging-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/'
  REACT_APP_PROD_IMAGE_UPLOAD_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/doges-on-trial/doge-images'

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER='<provider>'
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS='<address>'
  REACT_APP_PROD_IMAGES_BASE_URL='https://production-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/'
  REACT_APP_PROD_IMAGE_UPLOAD_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/production/doges-on-trial/doge-images'
