[build.environment]
  NODE_VERSION='9.4.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER="http://localhost:8545"
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS="0x6373dd366660306115fbec343334e470886d24a5"
  REACT_APP_PROD_IMAGES_BASE_URL="https://staging-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/"
  REACT_APP_PROD_IMAGE_UPLOAD_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/doges-on-trial/doge-images"
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL="https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings"

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER="http://localhost:8545"
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS="0xabfcdcc7baae6021118843717c7736876187637f"
  REACT_APP_PROD_IMAGES_BASE_URL="https://production-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/"
  REACT_APP_PROD_IMAGE_UPLOAD_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/doges-on-trial/doge-images"
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL="https://hgyxlve79a.execute-api.us-east-2.amazonaws.com/production/user-settings"
