[build.environment]
  NODE_VERSION='9.4.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_PROD_ETHEREUM_PROVIDER='http://localhost:8545'
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS='0x453f870c0a736813e4f429a40a7922c45dd0314b'
  REACT_APP_PROD_IMAGES_BASE_URL='https://staging-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/'
  REACT_APP_PROD_IMAGE_UPLOAD_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/doges-on-trial/doge-images'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/staging/user-settings'

[context.production.environment]
  REACT_APP_PROD_ETHEREUM_PROVIDER='<provider>'
  REACT_APP_PROD_ARBITRABLE_PERMISSION_LIST_ADDRESS='<address>'
  REACT_APP_PROD_IMAGES_BASE_URL='https://production-doges-on-trial-doge-images.s3.us-east-2.amazonaws.com/'
  REACT_APP_PROD_IMAGE_UPLOAD_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/production/doges-on-trial/doge-images'
  REACT_APP_PROD_PATCH_USER_SETTINGS_URL='https://8aoprv935h.execute-api.us-east-2.amazonaws.com/production/user-settings'
